//! Complete BETA-4 equipment fixtures for mob-placement and room-merge regressions.
use shpd_seedfinder_core::{
    catalog::item, main_world::CanonicalMainWorldGenerator, search::WorldGenerator,
    seed::DungeonSeed,
};

#[test]
fn mob_placement_and_room_merges_preserve_all_later_equipment() {
    // Official BETA-4 JAR SHA-256:
    // 76f6983e7b619267666621de9f1ecbbc3645d4925c2c446736987c3011b9dfd1
    // Generated by tooling/parity/BatchEquipmentOracle.java, including the Imp vault.
    for line in include_str!("fixtures/beta4-mob-retry-equipment.txt").lines() {
        let (seed, expected) = line.split_once('|').unwrap();
        let seed = DungeonSeed::new(seed.parse().unwrap()).unwrap();
        let world = CanonicalMainWorldGenerator.generate(seed, 24);
        let mut actual = world
            .items
            .iter()
            // This fixture pins equipment, before catalyst offers and artifacts were exposed.
            .filter(|i| {
                !matches!(
                    item(i.item).kind,
                    shpd_seedfinder_core::catalog::ItemKind::Trinket
                        | shpd_seedfinder_core::catalog::ItemKind::Artifact
                )
            })
            .map(|i| {
                format!(
                    "{},{:?},{},{},{},{}",
                    i.depth,
                    i.source,
                    item(i.item).stable_id,
                    i.upgrade,
                    u8::from(i.cursed),
                    i.effect.map_or("-", |e| e.wire_name())
                )
            })
            .collect::<Vec<_>>();
        actual.sort();
        assert_eq!(actual.join(";"), expected, "seed {}", seed.to_code());
    }
}
