//! Complete 4.0.1 equipment fixtures for mob-placement and room-merge regressions.
use shpd_seedfinder_core::{
    catalog::item, main_world::CanonicalMainWorldGenerator, search::WorldGenerator,
    seed::DungeonSeed,
};

#[test]
fn mob_placement_and_room_merges_preserve_all_later_equipment() {
    // Official 4.0.1 JAR SHA-256:
    // 452a4b3811d271ff6078ed352905516d3a48aeac310b4b6609cbb7f44bf534ea
    // Generated by tooling/oracle-4.0, including the Imp vault.
    for line in include_str!("fixtures/v4.0.1-mob-retry-equipment.txt").lines() {
        let (seed, expected) = line.split_once('|').unwrap();
        let seed = DungeonSeed::new(seed.parse().unwrap()).unwrap();
        let world = CanonicalMainWorldGenerator.generate(seed, 24);
        let mut actual = world
            .items
            .iter()
            // This fixture pins equipment, before catalyst offers and artifacts were exposed.
            .filter(|i| {
                !matches!(
                    item(i.item).kind,
                    shpd_seedfinder_core::catalog::ItemKind::Trinket
                        | shpd_seedfinder_core::catalog::ItemKind::Artifact
                )
            })
            .map(|i| {
                format!(
                    "{},{:?},{},{},{},{}",
                    i.depth,
                    i.source,
                    item(i.item).stable_id,
                    i.upgrade,
                    u8::from(i.cursed),
                    i.effect.map_or("-", |e| e.wire_name())
                )
            })
            .collect::<Vec<_>>();
        actual.sort();
        assert_eq!(actual.join(";"), expected, "seed {}", seed.to_code());
    }
}
