//! End-to-end observations from separate 65,536- and 262,144-seed sweeps, generated by
//! `examples/probability_sweep.rs`. Covers room/deck dependencies and the
//! Blacksmith/vault biases found by the broad sweep. The fixture stores only
//! exact match counts; estimates are always computed afresh.
use shpd_seedfinder_core::{json_query, probability::estimate_match_probability};

#[test]
fn vault_enchantments_respect_the_reward_shelf() {
    for document in [
        r#"{"requirements":[{"kind":"armor","tier":{"exact":2},"effect":"any_enchantment","source":"vault_treasure"}]}"#,
        r#"{"requirements":[{"kind":"thrown_weapon","tier":{"exact":2},"effect":"any_enchantment","source":"vault_treasure"}]}"#,
    ] {
        let query = json_query::decode(document).unwrap();
        assert!(
            estimate_match_probability(&query) < f64::EPSILON,
            "{document}"
        );
    }
}

#[test]
fn first_floor_competition_tracks_independent_random_query_observations() {
    // 65,536 validation seeds on the evenly spaced grid (offset zero),
    // independent of the 2,000,000-seed first-floor calibration stream.
    for (hits, document) in [
        (
            20.0,
            r#"{"max_depth":1,"requirements":[{"kind":"weapon","tier":{"at_most":4}},{"kind":"ring"},{"kind":"melee_weapon","upgrade":{"at_least":1}},{"kind":"wand"}]}"#,
        ),
        (
            47.0,
            r#"{"max_depth":1,"requirements":[{"kind":"armor"},{"kind":"wand"},{"kind":"armor"},{"kind":"melee_weapon","uncursed":true}]}"#,
        ),
        (
            146.0,
            r#"{"max_depth":1,"requirements":[{"kind":"wand"},{"kind":"ring","uncursed":true},{"kind":"armor"}]}"#,
        ),
    ] {
        let prediction = estimate_match_probability(&json_query::decode(document).unwrap());
        let expected_hits = prediction * 65_536.0;
        assert!(
            (expected_hits - hits).abs() <= 0.35 * hits + 4.0 * hits.sqrt(),
            "{document}: predicted {expected_hits}, observed {hits}"
        );
    }
}

#[test]
fn estimates_track_held_out_room_and_reward_queries() {
    let mut compared = 0;
    for document in [
        include_str!("fixtures/probability-heldout.json"),
        include_str!("fixtures/probability-overnight.json"),
        include_str!("fixtures/probability-source-counts.json"),
        include_str!("fixtures/probability-random-heldout.json"),
    ] {
        let observations: serde_json::Value = serde_json::from_str(document).unwrap();
        let samples = observations["samples"].as_f64().unwrap();
        for case in observations["cases"].as_array().unwrap() {
            let query = json_query::decode(&case["query"].to_string()).unwrap();
            let prediction = estimate_match_probability(&query);
            let hits = case["hits"].as_f64().unwrap();
            assert!(prediction.is_finite() && (0.0..=1.0).contains(&prediction));
            // Four-sigma Wilson interval, widened by the documented 35% model
            // allowance. Zero-hit overestimates are checked too. Sparse cases do
            // not establish accuracy, but remain useful one-sided upper bounds.
            let observed = hits / samples;
            let center = (observed + 8.0 / samples) / (1.0 + 16.0 / samples);
            let half = 4.0
                * (observed * (1.0 - observed) / samples + 4.0 / (samples * samples)).sqrt()
                / (1.0 + 16.0 / samples);
            assert!(
                prediction >= (center - half) / 1.35
                    && prediction <= ((center + half) * 1.35).min(1.0),
                "{}: predicted {prediction}, observed {hits}/{samples}",
                case["query"]
            );
            compared += 1;
        }
    }
    assert!(compared >= 400);
}
