#!/usr/bin/env python3
"""Generate map inspection text from the pinned Java game's English messages.

Run with --source-dir containing items.properties, plants.properties, both
Exotic*.java files and ItemSpriteSheet.java for an offline regeneration.
Otherwise fetch the pinned files.
Only static description text is included: hero-dependent formatted sentences and
paragraphs are omitted rather than displaying unresolved Java format arguments.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
from urllib.request import urlopen

REVISION = "2bb34a4e91d29c8785a9363cad6ddfe5122b1d4f"
ROOT = Path(__file__).resolve().parents[1]
BASE = f"https://raw.githubusercontent.com/00-Evan/shattered-pixel-dungeon/{REVISION}/core/src/main/"
FILES = {
    "ItemSpriteSheet.java": "java/com/shatteredpixel/shatteredpixeldungeon/sprites/ItemSpriteSheet.java",
    "items.properties": "assets/messages/items/items.properties",
    "plants.properties": "assets/messages/plants/plants.properties",
    "ExoticPotion.java": "java/com/shatteredpixel/shatteredpixeldungeon/items/potions/exotic/ExoticPotion.java",
    "ExoticScroll.java": "java/com/shatteredpixel/shatteredpixeldungeon/items/scrolls/exotic/ExoticScroll.java",
}


def normalize(value):
    return re.sub(r"[^a-z0-9$]", "", value.lower())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path)
    args = parser.parse_args()
    sources = {name: (args.source_dir / name).read_bytes() if args.source_dir else urlopen(BASE + path).read() for name, path in FILES.items()}
    messages = {}
    for file in ("items.properties", "plants.properties"):
        for line in sources[file].decode().splitlines():
            if not line or line.startswith("#"):
                continue
            key, value = line.split("=", 1)
            messages[key] = value.replace(r"\n", "\n").replace(r"\'", "'").replace(r'\"', '"')
    records = {}
    by_name = {}
    for key, name in messages.items():
        if not key.endswith(".name") or "%" in name:
            continue
        prefix = key[:-5]
        desc = messages.get(prefix + ".desc", messages.get(prefix + ".desc_1", ""))
        if prefix.startswith("plants.") and prefix.endswith("$seed"):
            desc = messages["plants.plant$seed.info"].replace("%s", messages.get(prefix[:-5] + ".desc", ""))
        if prefix in ("items.journal.alchemypage", "items.journal.guidepage"):
            desc = desc.split("\n\n", 1)[0]
        # Preserve original wording. Dynamic sentences need hero/depth state
        # that an item-type tooltip does not claim to know.
        paragraphs = []
        for paragraph in desc.split("\n\n"):
            sentences = re.split(r"(?<=[.!?])\s+", paragraph)
            static = [s for s in sentences if not re.search(r"%(?:\d+\$)?[\d.]*[a-zA-Z]", s)]
            if static:
                paragraphs.append(" ".join(static))
        desc = "\n\n".join(paragraphs).replace("_", "").replace("%%", "%")
        if not desc:
            continue
        identifier = normalize(prefix.rsplit(".", 1)[-1])
        records[identifier] = (name[0].upper() + name[1:], desc)
        by_name[normalize(name)] = identifier
    catalog = json.loads((ROOT / "android/app/src/main/assets/third_party/shattered-pixel-dungeon/catalog-v4.0.0.json").read_text())
    for item in catalog["entries"]:
        identifier = by_name.get(normalize(item["name"]))
        if identifier is None:
            raise ValueError(f"Missing Java description: {item['id']}")
        records[normalize(item["id"])] = records[identifier]
    aliases = {
        "Ration": "Food", "HourglassSandBag": "TimekeepersHourglass$Sandbag",
        "ArcaneStylus": "Stylus", "ShatteredPot": "Honeypot$ShatteredPot",
        "DoubleBomb": "Bomb$DoubleBomb", "Guidebook$GuidePage": "GuidePage",
    }
    for file in ("ExoticPotion.java", "ExoticScroll.java"):
        for regular, exotic in re.findall(r"regToExo.put\((\w+)\.class, (\w+)\.class\)", sources[file].decode()):
            aliases["Exotic" + regular] = exotic
    for key in list(records):
        if key.endswith("$seed"):
            aliases[key.replace("$", "")] = key
    for alias, target in aliases.items():
        records[normalize(alias)] = records[normalize(target)]
    output = ["// Generated by scripts/generate-item-text.py; do not edit.",
              "// Shattered Pixel Dungeon v4.0.0, GPL-3.0-or-later.",
              f"// Source revision: {REVISION}"]
    for name, data in sources.items():
        output.append(f"// {name}: sha256 {hashlib.sha256(data).hexdigest()}")
    output += ["#[rustfmt::skip]", "pub(super) const ITEM_TEXT: &[(&str, &str, &str)] = &["]
    for key, (name, desc) in sorted(records.items()):
        output.append("    (" + ", ".join(json.dumps(s, ensure_ascii=False) for s in (key, name, desc)) + "),")
    output += ["];", ""]
    # Identity glyphs, independently of the randomized bottle/rune/gem image.
    java_icons = sources["ItemSpriteSheet.java"].decode().split("class Icons {", 1)[1]
    icon_records = {}
    categories = {"RINGS": ["RingOf" + name for name in (
        "Accuracy", "Arcana", "Elements", "Energy", "Evasion", "Force", "Furor",
        "Haste", "Might", "Sharpshooting", "Tenacity", "Wealth")]}
    for file, category in (("ExoticPotion.java", "POTIONS"), ("ExoticScroll.java", "SCROLLS")):
        pairs = re.findall(r"regToExo.put\((\w+)\.class, (\w+)\.class\)", sources[file].decode())
        categories[category] = [regular for regular, _ in pairs]
        categories["EXOTIC_" + category] = [exotic for _, exotic in pairs]
    for category, classes in categories.items():
        x, y = map(int, re.search(r"int " + category + r"\s*=\s*xy\((\d+), (\d+)\)", java_icons).groups())
        base = x - 1 + 16 * (y - 1)
        constants = re.findall(r"int (\w+)\s*=\s*" + category + r"\+(\d+)", java_icons)
        assert len(constants) == len(classes) == 12
        for constant, offset in constants:
            index = base + int(offset)
            width, height = map(int, re.search(r"assignIconRect\(\s*" + constant + r",\s*(\d+),\s*(\d+)\s*\)", java_icons).groups())
            icon_records[normalize(classes[int(offset)])] = [index % 16 * 8, index // 16 * 8, width, height]
    for alias, target in aliases.items():
        if normalize(target) in icon_records:
            icon_records[normalize(alias)] = icon_records[normalize(target)]
    for item in catalog["entries"]:
        identifier = by_name.get(normalize(item["name"]))
        if identifier in icon_records:
            icon_records[normalize(item["id"])] = icon_records[identifier]
    output += ["#[rustfmt::skip]", "pub(super) const ITEM_ICONS: &[(&str, [u16; 4])] = &["]
    for key, rect in sorted(icon_records.items()):
        output.append(f"    ({json.dumps(key)}, {rect}),")
    output += ["];", ""]
    (ROOT / "crates/seedfinder-core/src/level_map/item_text.rs").write_text("\n".join(output))
    print(f"Generated {len(records)} item descriptions")


if __name__ == "__main__":
    main()
